"""classes table

Revision ID: 211330fb99ba
Revises: 5c38e55a543f
Create Date: 2022-10-03 01:21:23.218869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '211330fb99ba'
down_revision = '5c38e55a543f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classes_timestamp'), 'classes', ['timestamp'], unique=False)
    op.drop_index('ix_class_timestamp', table_name='class')
    op.drop_table('class')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('class_name', sa.VARCHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_class_timestamp', 'class', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_classes_timestamp'), table_name='classes')
    op.drop_table('classes')
    # ### end Alembic commands ###
