"""group table with timestamp

Revision ID: 2eaf0c0b9928
Revises: b653fa3720da
Create Date: 2022-10-10 12:25:00.354585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eaf0c0b9928'
down_revision = 'b653fa3720da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_group_timestamp'), 'group', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_group_timestamp'), table_name='group')
    op.drop_column('group', 'timestamp')
    # ### end Alembic commands ###
