"""classes table

Revision ID: 5c38e55a543f
Revises: 3be3e222b1c5
Create Date: 2022-10-03 00:11:27.636493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c38e55a543f'
down_revision = '3be3e222b1c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class', sa.Column('class_name', sa.String(length=64), nullable=True))
    op.drop_column('class', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class', sa.Column('name', sa.VARCHAR(length=64), nullable=True))
    op.drop_column('class', 'class_name')
    # ### end Alembic commands ###
