"""add class name in group table

Revision ID: 6493f55a7735
Revises: f8ad936a2d6a
Create Date: 2023-02-12 22:54:02.671440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6493f55a7735'
down_revision = 'f8ad936a2d6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('class_name', sa.String(length=64), nullable=True))
    op.create_foreign_key(None, 'group', 'classes', ['class_name'], ['class_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'group', type_='foreignkey')
    op.drop_column('group', 'class_name')
    # ### end Alembic commands ###
