"""added stuff to classes

Revision ID: 68e59e3f841a
Revises: fa9c635166c5
Create Date: 2023-03-08 00:26:01.274874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68e59e3f841a'
down_revision = 'fa9c635166c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_column('class_grade')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_grade', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
