"""change group grade from int to numeric

Revision ID: 7a07d11f6bfe
Revises: 548f3fa5f149
Create Date: 2023-05-06 17:33:46.237607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a07d11f6bfe'
down_revision = '548f3fa5f149'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.alter_column('grade',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.alter_column('grade',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
