"""empty message

Revision ID: 9604bb4d07d6
Revises: 
Create Date: 2023-04-25 15:35:17.476579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9604bb4d07d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subgroup')
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.Integer(), nullable=True))
        batch_op.drop_column('has_sub')
        batch_op.drop_column('_grade')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_grade', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('has_sub', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('grade')

    op.create_table('subgroup',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('grade', sa.INTEGER(), nullable=True),
    sa.Column('class_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('main_group_name', sa.VARCHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['main_group_name'], ['group.name'], name='fk_subgroup_main_group_name_group'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
