"""update group table

Revision ID: f8ad936a2d6a
Revises: 2eaf0c0b9928
Create Date: 2023-02-12 20:23:29.041828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8ad936a2d6a'
down_revision = '2eaf0c0b9928'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('group_type', sa.String(length=10), nullable=True))
    op.drop_column('group', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('type', sa.VARCHAR(length=10), nullable=True))
    op.drop_column('group', 'group_type')
    # ### end Alembic commands ###
